version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deserializing_avro_schema/Dockerfile # Change here to used DockerFile
    networks:
      - test_net
    volumes:
      - .:/code/
    entrypoint: ./deserializing_avro_schema/local_entrypoint.sh
    depends_on:
      - karapace-registry

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: faust-poc-zookeeper
    ports:
      - "2181:2181"
    networks:
      - test_net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    container_name: faust-poc-kafka
    ports:
      - "9092:9092" # Kafka
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - test_net
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=faust-poc-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://faust-poc-kafka:29092,PLAINTEXT_HOST://faust-poc-kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_OFFSETS_REPLICATION_FACTOR=1
      - KAFKA_CFG_CONFLUENT_SCHEMA_REGISTRY_URL=http://faust-poc-karapace-registry:8081
    # command: >
    #   bash -c
    #     "sleep 10s &&
    #     /opt/bitnami/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic 'my-topic'"


  karapace-registry:
    image: aivenoy/karapace:latest
    container_name: faust-poc-karapace-registry
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - test_net
    environment:
      KARAPACE_ADVERTISED_HOSTNAME: faust-poc-karapace-registry
      KARAPACE_BOOTSTRAP_URI: faust-poc-kafka:29092
      KARAPACE_PORT: 8081
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_CLIENT_ID: karapace
      KARAPACE_GROUP_ID: faust-poc-karapace-registry
      KARAPACE_MASTER_ELIGIBITY: "true"
      KARAPACE_TOPIC_NAME: _schemas
      KARAPACE_LOG_LEVEL: WARNING
      KARAPACE_COMPATIBILITY: FULL


networks:
  test_net: